In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import time
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [2]:
CollegeTrain = pd.read_csv("CollegeTrain.csv", index_col=0)
CollegeTest = pd.read_csv("CollegeTest.csv", index_col=0)

In [3]:
# Adjusting dataset and the samples
x_train= CollegeTrain.sample(frac = 0.05, random_state=0)

y_train = x_train['Outcome']
x_train = x_train.drop(['Outcome'], axis = 1)

x_test = CollegeTest.sample(n=100, random_state=0)

y_test = x_test['Outcome']
x_test = x_test.drop(['Outcome'], axis = 1)

In [4]:
x_train

,Private,Apps,Accept,Enroll,Top10perc,Top25perc,F.Undergrad,P.Undergrad,Outstate,Room.Board,Books,Personal,PhD,Terminal,S.F.Ratio,perc.alumni,Expend
New Mexico Institute of Mining and Tech.,0,787,601,233,40,73,1017,411,5376,3214,600,1100,99,100,13.7,11,9241
Arkansas College (Lyon College),1,708,334,166,46,74,530,182,8644,3922,500,800,79,88,12.6,24,14579
Millersville University of Penn.,0,6011,3075,960,22,60,5146,1532,7844,3830,450,1258,72,74,16.8,20,7832
Mount Mercy College,1,368,317,159,20,49,806,542,10500,3555,500,2285,44,50,11.3,30,6695
Mount St. Mary's College,1,657,537,113,37,90,1039,466,12474,5678,630,1278,53,71,11.9,19,10613
Keene State College,0,3121,2446,822,5,19,3480,776,7870,4157,500,1150,73,73,16.1,13,6195
University of San Francisco,1,2306,1721,538,23,48,4309,549,13226,6452,750,2450,86,86,13.6,8,10074
Claflin College,1,1196,697,499,21,47,959,13,4412,2460,500,1000,69,69,16.9,31,7083
American International College,1,1420,1093,220,9,22,1018,287,8700,4780,450,1400,78,84,14.7,19,7355
Southwest State University,0,1047,938,511,13,33,2091,546,4285,2750,600,1800,58,75,16.5,31,6591
University of Maine at Machias,0,441,369,172,17,45,633,317,6600,3680,600,400,46,46,15.1,4,5935
Rider University,1,3586,2424,730,16,31,2748,1309,13250,5420,700,3100,84,92,12.3,23,11299
Mississippi University for Women,0,480,405,380,19,46,1673,1014,4386,2217,600,1500,49,54,15.8,8,5704
Phillips University,1,692,576,174,19,50,597,83,10500,3860,600,940,58,64,11.6,19,8990
Columbia College MO,1,314,158,132,10,28,690,5346,8294,3700,400,900,87,87,15.3,2,5015
York College of Pennsylvania,1,2989,1855,691,28,63,2988,1726,4990,3560,500,1250,75,75,18.1,28,4509
Drury College,1,700,650,314,33,66,1065,48,8730,3523,500,750,82,92,13.2,35,9303
University of Wisconsin-Superior,0,910,910,342,14,53,1434,417,7032,2780,550,1960,75,81,15.2,15,6490
University of Richmond,1,5892,2718,756,46,72,2854,594,14500,3285,700,1125,75,89,11.7,32,11984
University of Vermont,0,7663,6008,1735,18,51,7353,1674,15516,4928,500,990,87,90,9.9,10,12646
Concordia University CA,1,688,497,144,30,75,641,101,10800,4440,570,1515,55,60,13.1,13,8415
Simmons College,1,1003,782,295,23,53,1144,160,16160,6950,500,1200,74,81,8.9,33,14086
Central Connecticut State University,0,4158,2532,902,6,24,6394,3881,5962,4444,500,985,69,73,16.7,4,4900
Bridgewater College,1,838,673,292,22,53,881,55,10265,4725,560,875,68,73,13.2,24,8655
Southern California College,1,385,340,193,18,38,784,127,9520,4124,630,1818,63,65,18.6,11,8219
Arkansas Tech University,0,1734,1729,951,12,52,3602,939,3460,2650,450,1000,57,60,19.6,5,4739
Bryn Mawr College,1,1465,810,313,71,95,1088,16,18165,6750,500,1200,100,100,12.3,49,17449
Cabrini College,1,599,494,224,8,28,1035,446,10518,6250,300,300,59,76,16.5,36,7117
Brigham Young University at Provo,1,7365,5402,4615,48,82,27378,1253,2340,3580,860,1220,76,76,20.5,40,7916

In [5]:
y_train

New Mexico Institute of Mining and Tech.     low
Arkansas College (Lyon College)              low
Millersville University of Penn.            high
Mount Mercy College                          low
Mount St. Mary's College                    high
Keene State College                          low
University of San Francisco                  low
Claflin College                              low
American International College              high
Southwest State University                   low
University of Maine at Machias               low
Rider University                            high
Mississippi University for Women             low
Phillips University                          low
Columbia College MO                          low
York College of Pennsylvania                high
Drury College                               high
University of Wisconsin-Superior             low
University of Richmond                      high
University of Vermont                       high
Concordia University CA                      low
Simmons College                             high
Central Connecticut State University         low
Bridgewater College                         high
Southern California College                  low
Arkansas Tech University                     low
Bryn Mawr College                           high
Cabrini College                             high
Brigham Young University at Provo            low
Name: Outcome, dtype: object

In [6]:
x_test

,Private,Apps,Accept,Enroll,Top10perc,Top25perc,F.Undergrad,P.Undergrad,Outstate,Room.Board,Books,Personal,PhD,Terminal,S.F.Ratio,perc.alumni,Expend
Westminster College MO,1,662,553,184,20,43,665,37,10720,4050,600,1650,66,70,12.5,20,7925
Millikin University,1,1444,1261,456,29,62,1788,95,11910,4378,450,965,60,77,11.4,25,8149
Augustana College IL,1,1879,1658,497,36,69,1950,38,13353,4173,540,821,78,83,12.7,40,9220
Guilford College,1,1202,1054,326,18,44,1410,299,13404,5160,450,1050,78,86,15.6,30,9114
Santa Clara University,1,4019,2779,888,40,73,3891,128,13584,5928,630,1278,88,92,13.9,19,10872
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Schreiner College,1,584,413,131,19,51,521,99,8955,5900,500,1488,51,56,11.8,23,8545
Saint Anselm College,1,2095,1553,514,15,40,1873,94,12950,5400,450,1120,70,82,14.5,29,6719
Mercer University,1,2286,1668,564,37,70,2943,1260,11985,4081,400,1500,93,95,9.2,15,8995
Immaculata College,1,268,253,103,16,44,494,1305,10000,5364,500,1000,56,64,11.2,33,7305
Tri-State University,1,1262,1102,276,14,40,978,98,9456,4350,468,1323,53,53,12.8,24,7603

In [7]:
# training the decision tree classifier

clf = DecisionTreeClassifier(random_state=0)
clf = clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)

In [8]:
print('Accuracy Score:', accuracy_score(y_test, y_pred))

Accuracy Score: 0.64

In [9]:
test_acc = accuracy_score(y_test, y_pred)

In [10]:
  # Compute Bound
S2 = ((((test_acc*100)*((test_acc-1)**2))+(((1-test_acc)*100)*(test_acc**2)))/100)
S = S2**(1/2)
SB = 1.96*S/10

In [11]:
SB

0.09408

In [12]:
print('Lower bound:',test_acc-SB)
print('Higher bound:',test_acc+SB)

Lower bound: 0.54592
Higher bound: 0.7340800000000001

In [13]:
#Mi método:
lower_bound = test_acc - 1.96*(((1-test_acc)*test_acc)/100)**(1/2)

In [14]:
lower_bound

0.54592

In [15]:
upper_bound = test_acc + 1.96*(((1-test_acc)*test_acc)/100)**(1/2)

In [16]:
upper_bound

0.7340800000000001

In [17]:
test_accs = []

for i in range(100):
    x_test = CollegeTest.sample(n=100, random_state=i)
    y_test = x_test['Outcome']
    x_test = x_test.drop(['Outcome'], axis = 1)
    y_pred = clf.predict(x_test)
    test_accs.append(accuracy_score(y_test, y_pred))
    
    

    
mean_test_acc = sum(test_accs)/len(test_accs)

In [18]:
mean_test_acc

0.6674000000000001

In [19]:
test_accs = []
lower_bounds = []
upper_bounds = []

for i in range(100):
    
    x_test = CollegeTest.sample(n=100, random_state=i)
    y_test = x_test['Outcome']
    x_test = x_test.drop(['Outcome'], axis = 1)
    
    y_pred = clf.predict(x_test)
    
    test_acc = accuracy_score(y_test, y_pred)
    test_accs.append(test_acc)
    
    lower_bound = test_acc - 1.96*(((1-test_acc)*test_acc)/100)**(1/2)
    upper_bound = test_acc + 1.96*(((1-test_acc)*test_acc)/100)**(1/2)
    
    lower_bounds.append(lower_bound)
    upper_bounds.append(upper_bound)

In [20]:
    
print("Media de test_Acc: ", sum(test_accs)/len(test_accs))
print("Media de lower_bounds: ", sum(lower_bounds)/len(lower_bounds))
print("Media de upper_bounds: ", sum(upper_bounds)/len(upper_bounds))

Media de test_Acc:  0.6674000000000001
Media de lower_bounds:  0.5753449782727248
Media de upper_bounds:  0.7594550217272746

In [21]:
print("Percentil lower_bounds: ", np.percentile(test_accs, 2.5))
print("Percentil upper_bounds: ", np.percentile(test_accs, 97.5))

Percentil lower_bounds:  0.61
Percentil upper_bounds:  0.7352499999999998

In [22]:
indiv_test_acc =[]
lower_bound = []
upper_bound = []

mean_test_acc = []
lower_bounds = []
upper_bounds = []
alpha = 2.5
for i in range(20):
    # preprocessing
    x_train= CollegeTrain.sample(frac = 0.05, random_state=i)

    y_train = x_train['Outcome']
    x_train = x_train.drop(['Outcome'], axis = 1)

    x_test = CollegeTest.sample(n=100, random_state=i)

    y_test = x_test['Outcome']
    x_test = x_test.drop(['Outcome'], axis = 1)

    # training the decision tree classifier
    clf = DecisionTreeClassifier(random_state=0)
    clf = clf.fit(x_train, y_train)
    y_pred = clf.predict(x_test)
    
    #individual preccision
    test_acc = accuracy_score(y_test, y_pred)
    indiv_test_acc.append(test_acc)
    
    #bounds of confidence interval for the test_acc
    lower_bound_aux = test_acc - 1.96*(((1-test_acc)*test_acc)/100)**(1/2)
    upper_bound_aux = test_acc + 1.96*(((1-test_acc)*test_acc)/100)**(1/2)
    lower_bound.append(lower_bound_aux)
    upper_bound.append(upper_bound_aux)
    
    #observed bounds and mean_test_Acc 
    test_accs = []
    for j in range(100):
        x_test = CollegeTest.sample(n=100, random_state=j)
        y_test = x_test['Outcome']
        x_test = x_test.drop(['Outcome'], axis = 1)
        y_pred = clf.predict(x_test)
        test_accs.append(accuracy_score(y_test, y_pred))
    
    mean_test_acc.append(sum(test_accs)/len(test_accs))
    lower_bounds.append(np.percentile(test_accs, alpha))
    upper_bounds.append(np.percentile(test_accs, 100-alpha))

In [23]:
frame = pd.DataFrame(columns = ["indiv_test_acc", "CI_lower_bound", "CI_upper_bound", "mean_test_acc", "observed_lower_bound", "observed_upper_bound"])
frame["indiv_test_acc"] = indiv_test_acc
frame["CI_lower_bound"] = lower_bound
frame["CI_upper_bound"] = upper_bound
frame["mean_test_acc"] = mean_test_acc
frame["observed_lower_bound"] = lower_bounds
frame["observed_upper_bound"] = upper_bounds

In [24]:

frame

,indiv_test_acc,CI_lower_bound,CI_upper_bound,mean_test_acc,observed_lower_bound,observed_upper_bound
0,0.64,0.545920,0.734080,0.6674,0.61000,0.73525
1,0.59,0.493601,0.686399,0.6240,0.55000,0.69000
2,0.62,0.524864,0.715136,0.6806,0.61000,0.74525
3,0.61,0.514401,0.705599,0.6726,0.61000,0.74000
4,0.63,0.535370,0.724630,0.6740,0.62000,0.73525
5,0.71,0.621063,0.798937,0.6086,0.54475,0.68000
6,0.61,0.514401,0.705599,0.5793,0.52000,0.63525
7,0.71,0.621063,0.798937,0.7256,0.67000,0.79000
8,0.67,0.577838,0.762162,0.7425,0.67475,0.80000
9,0.71,0.621063,0.798937,0.6817,0.62475,0.76000
10,0.73,0.642984,0.817016,0.6829,0.61475,0.74000
11,0.78,0.698808,0.861192,0.7431,0.67000,0.82000
12,0.64,0.545920,0.734080,0.6598,0.60000,0.71525
13,0.59,0.493601,0.686399,0.5721,0.52000,0.63525
14,0.73,0.642984,0.817016,0.7007,0.63475,0.76525
15,0.74,0.654028,0.825972,0.7726,0.71000,0.83000
16,0.68,0.588571,0.771429,0.6647,0.59950,0.72525
17,0.50,0.402000,0.598000,0.5549,0.49000,0.62525
18,0.79,0.710168,0.869832,0.7085,0.64475,0.77000
19,0.56,0.462708,0.657292,0.6221,0.56000,0.68525

In [41]:
precision = 130/150

In [42]:
precision

0.8666666666666667

In [43]:
lower_bound = precision - 1.96*(((1-precision)*precision)/100)**(1/2)

In [44]:
upper_bound = precision + 1.96*(((1-precision)*precision)/100)**(1/2)

In [45]:
print("Media de lower_bounds: ", lower_bound)
print("Media de upper_bounds: ",upper_bound)

Media de lower_bounds:  0.800039478355721
Media de upper_bounds:  0.9332938549776124

In [46]:
precision = 115/150

precision

lower_bound = precision - 1.96*(((1-precision)*precision)/100)**(1/2)

upper_bound = precision + 1.96*(((1-precision)*precision)/100)**(1/2)

print("Media de lower_bounds: ", lower_bound)
print("Media de upper_bounds: ",upper_bound)

Media de lower_bounds:  0.6837679600690632
Media de upper_bounds:  0.8495653732642703