# Importing Libraries

In [18]:
import pandas as pd
from pandas import read_csv
import numpy as np

# Importing Data

In [5]:
# pandas data frame
train_df = read_csv("ML-A5-2022_train.csv", index_col=0)

# numpy array
train_np = train_df.values

In [15]:
train_df.dropna(how="all", axis=1)

,A1BG,A1CF,A2M-AS1,A2ML1,A2ML1-AS1,A2ML1-AS2,A3GALT2,A4GALT,A4GNT,AACS,...,ZSWIM9,ZUP1,ZXDA,ZXDB,ZXDC,ZYG11A,ZYG11B,ZZEF1,hsa-mir-423,label
C-1,0.0,0.0,low,NaN,low,NaN,NaN,0.0,0.0,0.0,...,NaN,low,0.0,0.0,0.0,0.0,0.0,medium,0.0,-1
C-2,0.0,0.0,high,0.0,low,0.0,0.0,0.0,NaN,0.0,...,NaN,low,0.0,NaN,NaN,0.0,0.0,low,NaN,-1
C-3,0.0,0.0,low,0.0,low,0.0,0.0,0.0,0.0,0.0,...,0.0,low,19.0,1.0,0.0,0.0,0.0,low,0.0,-1
C-4,0.0,NaN,low,0.0,low,0.0,0.0,0.0,0.0,0.0,...,NaN,low,NaN,0.0,0.0,0.0,NaN,low,0.0,-1
C-5,23.0,0.0,low,0.0,low,NaN,0.0,0.0,NaN,0.0,...,NaN,low,0.0,0.0,0.0,0.0,0.0,low,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
C-996,8.0,NaN,low,0.0,low,0.0,0.0,0.0,0.0,NaN,...,NaN,low,NaN,NaN,NaN,0.0,0.0,low,0.0,-1
C-997,0.0,0.0,low,0.0,low,0.0,0.0,NaN,NaN,7.0,...,0.0,low,NaN,0.0,0.0,0.0,5.0,medium,0.0,-1
C-998,0.0,0.0,low,0.0,low,0.0,0.0,NaN,0.0,0.0,...,0.0,low,0.0,0.0,0.0,0.0,0.0,low,0.0,-1
C-999,9.0,NaN,low,NaN,low,0.0,0.0,NaN,0.0,NaN,...,NaN,low,NaN,0.0,0.0,0.0,0.0,low,0.0,-1
C-1000,0.0,0.0,low,0.0,low,0.0,0.0,NaN,0.0,NaN,...,NaN,low,0.0,0.0,0.0,0.0,0.0,low,0.0,1

In [30]:
# Adjust to mode
train_df_noNan = train_df.fillna(train_df.mean())