In [1]:
import pandas as pd

In [2]:
train_df = pd.read_csv("ML-A5-2022_train.csv", index_col=0)
test_df = pd.read_csv("ML-A5-2022_test.csv", index_col=0)

In [3]:
train_df.head()

,A1BG,A1CF,A2M-AS1,A2ML1,A2ML1-AS1,A2ML1-AS2,A3GALT2,A4GALT,A4GNT,AACS,...,ZSWIM9,ZUP1,ZXDA,ZXDB,ZXDC,ZYG11A,ZYG11B,ZZEF1,hsa-mir-423,label
C-1,0.0,0.0,low,NaN,low,NaN,NaN,0.0,0.0,0.0,...,NaN,low,0.0,0.0,0.0,0.0,0.0,medium,0.0,-1
C-2,0.0,0.0,high,0.0,low,0.0,0.0,0.0,NaN,0.0,...,NaN,low,0.0,NaN,NaN,0.0,0.0,low,NaN,-1
C-3,0.0,0.0,low,0.0,low,0.0,0.0,0.0,0.0,0.0,...,0.0,low,19.0,1.0,0.0,0.0,0.0,low,0.0,-1
C-4,0.0,NaN,low,0.0,low,0.0,0.0,0.0,0.0,0.0,...,NaN,low,NaN,0.0,0.0,0.0,NaN,low,0.0,-1
C-5,23.0,0.0,low,0.0,low,NaN,0.0,0.0,NaN,0.0,...,NaN,low,0.0,0.0,0.0,0.0,0.0,low,0.0,1

## Impute

- NA: fill with median

## Categorical

- 0, 1, 2 -> {low, medium, high}

## Labels

{-1, 1} -> {0, 1}

## Feature selection

Keep features with highest variances

In [4]:
import numpy as np
from sklearn.impute import SimpleImputer

K = 1000

labels = train_df['label']
train_df['label'][labels == -1] = 0
train_modif_df = train_df.copy()
train_modif_df = train_modif_df.drop("label", axis=1)

train_modif_df = train_modif_df.replace({"low": 0, "medium":1, "high": 2})
train_modif_df.fillna(train_modif_df.median(), inplace=True)
X_df=train_modif_df.to_numpy()

variances = sorted([(np.var(X_df[:, i]), i) for i in range(X_df.shape[1])], reverse=True)
k_bests = [j for i,j in variances[:K]]

X_df = X_df[:, k_bests]

C:\Users\mathm\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys

In [5]:
train_modif_df.head()

,A1BG,A1CF,A2M-AS1,A2ML1,A2ML1-AS1,A2ML1-AS2,A3GALT2,A4GALT,A4GNT,AACS,...,ZSWIM8-AS1,ZSWIM9,ZUP1,ZXDA,ZXDB,ZXDC,ZYG11A,ZYG11B,ZZEF1,hsa-mir-423
C-1,0.0,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,1,0.0
C-2,0.0,0.0,2,0.0,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0,0.0
C-3,0.0,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0,19.0,1.0,0.0,0.0,0.0,0,0.0
C-4,0.0,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0,0.0
C-5,23.0,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0,0.0

In [6]:
len(X_df[0])

1000

## Modelling

In [ ]:
from sklearn.model_selection import KFold
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import AdaBoostClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import balanced_accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import RandomForestClassifier
from imblearn.over_sampling import SMOTE 
import lightgbm as lgb
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import VotingClassifier
from collections import Counter
kf = KFold(n_splits=12)

X, y = X_df, labels.values
i = 0

scores = []
scoresgrad = []

max_score = 0


for train_idx, test_idx in kf.split(X, y):
    
    X_tra, y_tra = X[train_idx], y[train_idx]
    X_test, y_test = X[test_idx], y[test_idx]
    sm=SMOTE(k_neighbors=15)
    X_train, y_train = sm.fit_resample(X_tra, y_tra)

    print('Resampled dataset shape %s' % Counter(y_train))
    
    #clf = AdaBoostClassifier(DecisionTreeClassifier(max_depth=1),n_estimators=201,algorithm='SAMME.R' )
    model = lgb.LGBMClassifier(learning_rate=0.05,num_iterations=202)
    clf=AdaBoostClassifier(n_estimators=202)
    clf2 = GradientBoostingClassifier(n_estimators=202,loss='exponential',min_samples_split=3,min_samples_leaf=5,max_features='auto',learning_rate=0.9)
    #eclf1 = VotingClassifier(estimators=[('ab', clf), ('gb', clf2)], voting='soft').fit(X_train, y_train)
    eclf1 = MLPClassifier(hidden_layer_sizes=(300,50) ,activation='tanh',solver='sgd', max_iter=500,batch_size=100).fit(X_train, y_train)
    y_pred = eclf1.predict(X_test)
    #y_predgrad = clf2.predict(X_test)
    score = balanced_accuracy_score(y_test, y_pred)
    #scoregrad = balanced_accuracy_score(y_test, y_predgrad)

    
    scores.append(score)
    #scoresgrad.append(scoregrad)
    print(f"Fold {i}: BCR boost={score}")
    #print(f"Fold {i}: BCR grad={scoregrad}")
    i+=1
    
print(f"Average BCR boost:{np.mean(scores)}")
print(f"std :{np.std(scores)}")
#print(f"Average BCR grad:{np.mean(scoresgrad)}")

In [8]:

import matplotlib.pyplot as plt
print(f"Average BCR boost:{np.std(scores)}")

plt.hist(y)
plt.show()

Average BCR boost:0.05976610304697795